const mongoose = require('mongoose');
const userRouter=require('./routes/usersRouter.js')
const taskRouter=require('./routes/taskRouter.js') 
const express = require('express')
require('dotenv').config()
const app=express()
console.log(process.env.DATABASE_URL)
mongoose.connect('mongodb://localhost/task-manager',()=>console.log('connected'),(err)=>console.log(err))
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use('/api/users',userRouter)
app.use('/api/task',taskRouter)
app.listen(3000,()=>console.log('http://localhost:3000'))